import { Component } from '@angular/core';

interface Mapping {
  [key: string]: string;
}

interface valuePathMapping {
  [key: string]: [string, string];
}

@Component({
  selector: 'app-creat-quiz',
  templateUrl: './creat-quiz.component.html',
  styleUrls: ['./creat-quiz.component.scss'],
})
export class CreatQuizComponent {
  show: boolean = false;

  objectKeys: (o: object) => string[] = Object.keys;

  boardMapping: Mapping = {
    CBSE: 'CBSE',
    ICSE: 'ICSE',
  };
  stateMapping: Mapping = {
    IN: 'Central',
    AP: 'Andhra Pradesh',
  };
  languageIsoCodeMapping: Mapping = {
    EN: 'English',
    HI: 'Hindi',
  };
  // subjectMapping: Mapping = {
  //   PHY: 'Physics',
  //   CHM: 'Chemistry',
  //   BIO: 'Biology',
  //   SCE: 'Science',
  //   MTH: 'Mathematics',
  //   ENG: 'English',
  //   SSC: 'Social Science',
  //   GEO: 'Geography',
  //   CSE: 'Computer Science',
  //   HIN: 'Hindi',
  // };

  subjectMapping: valuePathMapping = {
    MTH: ['Mathematics', '../../../assets/mathsimg.png'],
    PHY: ['Physics', '../../../assets/physicsimg.png'],
    CHM: ['Chemistry', '../../../assets/chemimg.png'],
    BIO: ['Biology', '../../../assets/bioimg.png'],
    SCE: ['Science', '../../../assets/scienceimg.png'],
    // TODO: what do with rest of the subjects that are not in design
  };
  subjectTypeMapping: Mapping = {
    STEM: 'STEM',
    ARTS: 'Arts & Humanities',
    BSCM: 'Business & Commerce',
    SSCE: 'Social Science',
    HEDU: 'Health Education',
    OEDU: 'Occupationale Education',
  };
  examTypeMapping: Mapping = {
    GENL: 'General',
    OLMP: 'Olympiad',
    IITJ: 'IIT-JEE',
    NEET: 'NEET',
    WBJE: 'WBJEE',
  };
  questionTypeMapping: Mapping = {
    MCQ: 'MCQ',
    FIB: 'Fill In The Blank',
    TNF: 'True & False',
  };
  generationTypeMapping: Mapping = {
    AI: 'Generated by AI',
    MN: 'Generated Manually',
  };
  difficultyLevelMapping: Mapping = {
    '01': 'Easy',
    '02': 'Moderate',
    '03': 'Complex',
    '04': 'Advanced',
    '05': 'Expert',
  };
  typeOfQuestion: Mapping = {
    ST: 'Story Telling',
    CP: 'Comparision Based',
    AT: 'Activity Based',
    EB: 'Example Based',
    EP: 'Expirement Based',
    DG: 'Direct Question',
  };

  classMapping: Mapping = {
    '1': 'Class 1',
    '2': 'Class 2',
    '3': 'Class 3',
    '4': 'Class 4',
    '5': 'Class 5',
    '6': 'Class 6',
    '7': 'Class 7',
  };

  openModal(): void {
    this.show = true;
  }

  closemodal(): void {
    this.show = false;
  }

  selectedFile: File | null = null;

  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.selectedFile = input.files[0];
    }
  }

  onDrop(event: DragEvent): void {
    event.preventDefault();
    this.handleFile(event.dataTransfer?.files || null);
  }

  handleFile(fileList: FileList | null): void {
    if (fileList && fileList.length > 0) {
      this.selectedFile = fileList[0];
    }
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
  }

  onDragLeave(event: DragEvent): void {
    event.preventDefault();
  }

  uploadFile(): void {
    if (this.selectedFile) {
      // Implement your file upload logic here
      console.log('Uploading file:', this.selectedFile);
      // Reset selectedFile after upload
      this.selectedFile = null;
    }
  }
}
